### ISSUE TITLE
`to_dataset_dict` stops due to Permission error / file access error

### ISSUE THREAD

**Issue by markusritschel** [intake/intake-esm#281]
Hi,
It happens to me from time to time that when I do a `to_dataset_dict()`, the method throws an error at some point due to a `Permission denied` access failure. This happens, when a file was moved or got restricted rights and the catalog was not rebuilt afterwards. Is it possible to somehow ignore files that cannot be found? Or could you implement this in `to_dataset_dict` somehow?

**Comment by andersy005** [comment]
@markusritschel,

I think this could lead to confusion to users since the expectation is that the files they see in the catalogs correspond to what they get in the loaded datasets. 

A more robust solution would consist in controlling this behavior at the catalog level i.e. 

 - Identify the attributes of the problematic files
 - Exclude these problematic files from the returned catalog subset via `col.search(...)` method
 - Load "Okay" files with `.to_dataset_dict()` as usual 
 
Would this solution work for you?

**Comment by markusritschel** [comment]
Hi @andersy005,
Yes, I did come up with a similar workaround. Also, the problem is pretty much solved since they update the catalog now more frequently.
From my side, we can close this issue.

**Comment by andersy005** [comment]
Thank you for the update, @markusritschel!
