### ISSUE TITLE
intake-esm for multi-dim zarr in cloud?

### ISSUE THREAD

**Issue by aaronspring** [intake/intake-esm#325]
Hi Anderson, 

I have a general question about the scope and purpose of intake-esm (which I love and use once a week) and its limits. 

We want to move S2S/SubX data to the cloud and think about data access. Essentially intake-esm takes raw model output and concatenates files together as specified in the json because cmip6 simulations are heterogeneous across activity_id. 

The data we want to provide in the cloud has the same specifications as the CMIP DCPP experiments. Many Members of forecasts, started/initialised in different years and run for some lead time. We have many variables and 10 models. 

Ryan suggests to preprocess the data into large zarrs per model (they have different init dates). https://github.com/pangeo-forge/staged-recipes/issues/17#issuecomment-766872196

That would be good for performance but sideline intake-esm, because we would only need to combine zarrs from different models. Or would you see a benefit of having intake-esm? imagine if cmip6 would only be the scenarioMIP simulations which were all stored in one zarr with member, model and experiment dimension. 

In such a setup, would intake-esm be useful or should we many just write a simple function get_subx(models)? Selecting variables, members or spatial domain would then all be handled by xarray.

Our discussion: https://github.com/judithberner/climpred_CESM1_S2S/issues/1#issuecomment-787101029

**Comment by andersy005** [comment]
Hi @aaronspring,

> That would be good for performance but sideline intake-esm, because we would only need to combine zarrs from different models.

If I am not mistaken, I think with a catalog in place, intake-esm is happy to do the subsetting work for you at the catalog level, and then propagating the information to the code that loads the data. What I gathered from the issues and comments you linked to, is that the structure of the resulting zarr stores will resemble to the raw outputs (i.e. history files in which you have multiple variables in a single file) that we get from most climate models. 

When you get a chance, can you take a look at this [notebook](https://intake-esm.readthedocs.io/en/latest/user-guide/multi-variable-assets.html) that demonstrates how to use intake-esm with multi-variable files and let me know if my assessment of your problem is accurate and or whether there are any similarities between multi variable datasets and the structure of your zarr stores?

> In such a setup, would intake-esm be useful or should we many just write a simple function get_subx(models)? Selecting variables, members or spatial domain would then all be handled by xarray.

Today intake-esm have *zero** *requirements* when it comes to the structure of the zarr stores. My recommendation is to go ahead and produce the zarr stores however you want and then we can work together to produce a catalog that will provide convenient access to the data for folks who want to use intake-esm. 


*: I am certain there are some assumptions within intake-esm, but I don't think these assumptions make intake-esm incompatible with your use case.

**Comment by aaronspring** [comment]
Thanks for the quick reply @andersy005.

> structure of the resulting zarr stores will resemble to the raw outputs (i.e. history files in which you have multiple variables in a single file)

Sorry, I was too short in my problem description. I meant the opposite: Our idea (backed by Ryan in https://github.com/pangeo-forge/staged-recipes/issues/17#issuecomment-766872196 for performance reasons (chunked for climpred `{'init':-1}`) ) is to aggregate raw model output into multi-simulation multi-var zarr stores.
We can do so, because our data is static (experiments from 1999 to 2017), very homogeneous, unlike the CMIP6 data with retractions and further uploads changing over time.

Please find a better example of our use-case here: https://nbviewer.jupyter.org/gist/aaronspring/65fdd121bc7353740063818c528e82eb

About "limits" of `intake-esm`: I rather meant what are the specific strengths of `intake-esm` over user writing your user defined functions for data access. For raw model output, `intake-esm` is a game changer, no doubt. For already high-dimensional zarrs as in the gist, it may not be needed so much, e.g. a simple xr.open_zarr wrapper achieves basically the same. Looking forward to your thoughts on this.
